### ISSUE TITLE
Running simple "hello world" JS script on NodeJS (tracking "epic")

### ISSUE THREAD

**Issue by castarco** [nuta/kerla#23]
I've run the following command in my Linux machine (to see which syscalls are being sent to the kernel for a very basic NodeJS program):
```bash
strace echo "console.log('hello')" | node
```
and I've got the following list (taking aside the ones already implemented):
- `access`
- `openat`
- `pread64`
- `mprotect`

some of this calls could be related to Bash and not NodeJS, but if instead I run this:
```bash
strace node example.js # with the same JS script as before
```
we obtain this list (confirming that they are needed for NodeJS too):
- [ ] `access`
- [ ] `openat`
- [ ] `pread64`
- [ ] `mprotect`
- [ ] `munmap`
- [ ] `set_robutst_list`
- [ ] `rt_sigprocmask`
- [ ] `prlimit64`
- [ ] `pipe2`
- [ ] `eventfd2`
- [ ] `clone`
- [ ] `madvise`
- [ ] `futex`: https://github.com/nuta/kerla/issues/2
- [ ] `epoll_ctl`: https://github.com/nuta/kerla/issues/19
- [ ] `epoll_wait`: https://github.com/nuta/kerla/issues/19
- [ ] `exit_group`

I hope this can be useful to guide the next steps for this roadmap ( https://github.com/nuta/kerla/projects/1 ).
